### PR TITLE
arm64: kernel 5.15: Enable VRF

### PR DESCRIPTION
**Pull request by taraschornyiplv**
Enable VRF in kernel config

### CODE REVIEW

**Review by paulmenzel — COMMENTED** [review]
For what use-case is that useful? Just for the test cases?

**Comment by taraschornyiplv** [comment]
We need this to configure VRF in DentOS

https://github.com/Marvell-switching/switchdev-prestera/wiki/virtual-router-interface-(vrf)

**Comment by taraschornyiplv** [comment]
reverify

**Review by eladnachman — APPROVED** [review]

**Comment by taraschornyiplv** [comment]
reverify

**Comment by taraschornyiplv** [comment]
reverify

**Comment by taraschornyiplv** [comment]
reverify

**Review by KanjiMonster — APPROVED** [review]
LGTM

**Comment by KanjiMonster** [comment]
Verified to be working following the example in https://docs.bisdn.de/network_configuration/virtual_routing_and_forwarding.html#iproute2 and pinging between both hosts. Pings succeeded and were offloaded.

**Pull request merged**
