### PR TITLE
prestera: Update prestera to v3.1.3

### PR DESCRIPTION
**Pull request by taraschornyiplv**
This is a bug fixing release
It includes AC5x port shifting issue and RX stability issue

Signed-off-by: Taras Chornyi <taras.chornyi@plvision.eu>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Thank you for the release.

s/releace/release/

> It includes AC5x port shifting issue and RX stability issue

Please link to the issues with the details.

As written in the past, please format the patch with `git format-patch`, and maybe even split it up.

**Comment by Mickey201** [comment]
> 
> > It includes AC5x port shifting issue and RX stability issue
> 
> Please link to the issues with the details.
> 
The related code change resolves a 'high-temp' SERDES issue located during manufacturing tests.
The code was integrated into the Firmware and will be included in the next PP driver release.

**Review by robimarko — APPROVED** [review]

**Comment by paulmenzel** [comment]
The patch is still just a plain diff, and not created with `git format-patch`.

**Review by eladnachman — APPROVED** [review]

**Comment by Mickey201** [comment]
> The patch is still just a plain diff, and not created with `git format-patch`.

Hi Paul, Your comment is clear; 
Currently, some of the patches are scripts-built based and therefore the format-patch info is missing.
We will do our best to handle it for the following commits.

**Pull request merged**
