### PR TITLE
dent-atrifact: Use Marvell FW v3.1.2

### PR DESCRIPTION
**Pull request by taraschornyiplv**
Update dent-artifact submodule  to include FW v3.1.2 from Marvell

Signed-off-by: Taras Chornyi <taras.chornyi@plvision.eu>

### CODE REVIEW

**Review by robimarko — APPROVED** [review]

**Review by Mickey201 — APPROVED** [review]

**Review by paulmenzel — COMMENTED** [review]
The submodule commit contains:

> Update Marvell fw image version v3.1.2
> 
> - Official FW release compatible with Marvell Switchdev Driver v3.1.1
> and later
> - Bug fixing - traffic drops after testing repeated reboots
> 
> Tested by Marvell Validation team on all based DNI/Accton platforms

Is it true, that only one bug is fixed?

**Comment by Mickey201** [comment]
> 
> Is it true, that only one bug is fixed?
Yes, Paul. only one issue was required to be resolved. 
Why do you sound surprised? We have a quite good validation team 🥇

**Comment by paulmenzel** [comment]
> > Is it true, that only one bug is fixed?
> 
> Yes, Paul. only one issue was required to be resolved. Why do you sound surprised? We have a quite good validation team

I didn’t mean to sound surprised. I just asked, because these terse commit messages leave room for interpretation.

It’d be great if you added a link to the issue/bug for the traffic dropping issue. As it’s binary firmware, it’s especially hard to verify changes, so it’‘d be great to have at least a way to reproduce the issue.

**Comment by jmpolom** [comment]
I agree with @paulmenzel that the lack of detail in commits, lack of a public detailed changelog or links to specific issues resolved make it nearly impossible for end users to determine what, exactly, is being fixed or supported when. We are to take it on faith or from third parties which is suboptimal. This needs to be improved.

**Comment by snobleaws** [comment]
Are we able to merge this?

**Comment by taraschornyiplv** [comment]
yes we are

**Pull request merged**
