### PR TITLE
Enhanced SFP support-Prestera Switchdev v2.8.0 driver

### PR DESCRIPTION
**Pull request by Mickey201**
Adding new SFP - GPIO support
Bug Fixing

Signed-off-by: Mickey Rachamim <mickeyr@marvell.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Thank you for the contribution.

1.  Could you please add git formatted patches with a commit message, which is signed off?
2.  Also, please add details, why it’s added to 5.6, if it’s present in 5.10, if it’s going to be backported.
3.  Please also add, how you tested this, to the commit message.

**Comment by Mickey201** [comment]
Hi @paulmenzel 
1.	Sorry, but not clear to me what do you mean by: “_add git formatted patches with a commit message_”.
2.	5.6 is currently the Stable version and it used by Amazon. 
        Similar change will be added soon also to 5.10 + Marvell support for LK 5.10.
3.	Tested with Accton/DNI platforms + 
                    Accton RX_LOSS fix (f7d78208391c480ef3c3b190874f9e5a362679c1)

**Comment by paulmenzel** [comment]
>     1. Sorry, but not clear to me what do you mean by: “_add git formatted patches with a commit message_”.

It should look like [`./packages/base/any/kernels/5.6-lts/patches/0001-arm64-dts-ls208x-remove-NXP-Erratum-A008585-from-LS2.patch`](https://github.com/dentproject/dentOS/blob/main/packages/base/any/kernels/5.6-lts/patches/0001-arm64-dts-ls208x-remove-NXP-Erratum-A008585-from-LS2.patch).

Basically, what problems are fixed and what improvements are there.

>     2. 5.6 is currently the Stable version and it used by Amazon.
>        Similar change will be added soon also to 5.10 + Marvell support for LK 5.10.

So, it’s not upstream yet. Please mention that in the commit message, and merge/pull request description.

>     3. Tested with Accton/DNI platforms +
>        Accton RX_LOSS fix ([f7d7820](https://github.com/dentproject/dentOS/commit/f7d78208391c480ef3c3b190874f9e5a362679c1))

On all platforms? Please mention the exact models in the commit message, and maybe even list the tests you run.

**Comment by paulmenzel** [comment]
See https://chris.beams.io/posts/git-commit/ for a good article on commit messages.

**Comment by paulmenzel** [comment]
@sonoble, it’d be great if you could comment, why review comments are ignored. The diff files for the Linux kernel not in git format-patch format are unreviewable and unmaintainable.

**Comment by sonoble** [comment]
> @sonoble, it’d be great if you could comment, why review comments are ignored. The diff files for the Linux kernel not in git format-patch format are unreviewable and unmaintainable.

This merge was not purposeful, we were working on why the branch was locked and I merged it during debugging. The code does need to go into the project, as we are on a tight timeline. 

There is no reason to remove it at this point as the code is working, so since it will be upstreamed to the Linux kernel, the upstreamed version will make it back into dentOS once it is reviewed and accepted.

Mickey stated that he will work on the comments that you have on the code.

**Pull request merged**
