### PR TITLE
[as4224/as5114] Add CPLD sub_version in onlp_sysi_platform_info_get()

### PR DESCRIPTION
**Pull request by brandonchuang**
Signed-off-by: Brandon Chuang <brandon_chuang@edge-core.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Please amend the commit message (and force push) and elaborate, what the problem is.

**Comment by brandonchuang** [comment]
Amended.

**Comment by paulmenzel** [comment]
Thank you.

> The sub version is also required.

What is it required for?

**Comment by brandonchuang** [comment]
> Thank you.
> 
> > The sub version is also required.
> 
> What is it required for?

The sub version is defined in the CPLD spec. (Register 0xFF)
I missed the field before and customer asked for it.

**Comment by paulmenzel** [comment]
Please change

> The sub version is also required.

to

> A sub version also exists, so display it too, as it’s good to have for informational purposes.

**Comment by brandonchuang** [comment]
> Please change
> 
> > The sub version is also required.
> 
> to
> 
> > A sub version also exists, so display it too, as it’s good to have for informational purposes.

Done.

**Review by paulmenzel — APPROVED** [review]
Thank you for amending the commit message.

It looks like, exposing the sub version is already implemented for the arm64_accton_as4564_26p, and this commit basically adds the same code.

PS: It’d be great, if you could unify both files in another merge/pull request.

    $ diff -u packages/platforms/accton/arm64/as4224/src/arm64_accton_as4224/module/src/sysi.c packages/platforms/accton/arm64/as4564-26p/onlp/builds/arm64_accton_as4564_26p/module/src/sysi.c

**Review by taraschornyiplv — APPROVED** [review]

**Review by eladnachman — APPROVED** [review]

**Pull request merged**
