### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by taraschornyiplv**
remove tx4810 platform

### CODE REVIEW

**Comment by taraschornyiplv** [comment]
recheck

**Comment by robimarko** [comment]
Why is TX4810 getting removed?

**Comment by taraschornyiplv** [comment]
> Why is TX4810 getting removed?

its a test PR to check new Jenkins provider integration.

**Comment by DhruvJ225** [comment]
test Jenkins build trigger

**Comment by taraschornyiplv** [comment]
recheck

**Pull request closed without merging**
