### PR TITLE
Update Marvell firmware to 3.0.1

### PR DESCRIPTION
**Pull request by snobleaws**
This pull request resolves issue #147 by updating the Marvell firmware driver to v3.0.1 which matches the driver version in the code from #145 
Signed-off-by: Steve Noble <snoble@sonn.com>

### CODE REVIEW

**Review by paulmenzel — CHANGES_REQUESTED** [review]
Thank you for pushing the fix. Some wishes as always:

Please amend the commit and elaborate, by mentioning, that currently the driver fails to load since commit …, paste the error message, reference https://github.com/dentproject/dentOS/issues/147.

**Comment by snobleaws** [comment]
This is still the same failure as before:

11:28:45 ---> dentos-build.sh
11:28:45 + sudo apt-get install -y binfmt-support
11:28:45 sudo: apt-get: command not found
11:28:45 Build step 'Execute shell' marked build as failure

**Review by taraschornyiplv — APPROVED** [review]

**Comment by jwagantall** [comment]
recheck

**Comment by snobleaws** [comment]
@paulmenzel any issues with my updated commit message?

**Review by robimarko — APPROVED** [review]

**Comment by paulmenzel** [comment]
> @paulmenzel any issues with my updated commit message?

No, you didn’t amend the commit message, but the merge/pull request description. Please run `git commit --amend` and then `git push -f`.

Please also add the tag below, so GitHub closes the issues automatically.

> Resolves: https://github.com/dentproject/dentOS/issues/147

**Comment by sonoble** [comment]
Should be fixed, waiting for the build to complete.

**Pull request merged**
