### PR TITLE
Temporary work around for apt.opennetlinux.org issue, fix amd64 build…

### PR DESCRIPTION
**Pull request by sonoble**
… by remove hw-management package

Signed-off-by: Steven Noble <snoble@sonn.com>

### CODE REVIEW

**Review by paulmenzel — CHANGES_REQUESTED** [review]
> Temporary work around for apt.opennetlinux.org issue, fix amd64 build by remove hw-management package

Please reword it (and also amend the commit message). Maybe:

> Do not install ONL-local packages to work around not-working apt.opennetlinux.org
> 
> Currently, the archive apt.opennetlinux.org is not functional, so do
> not install packages from this ONL-local repository, which currently
> is only the package *hw-management*. This fixes the build.

**Comment by sonoble** [comment]
Hi Paul,

I was able to recover the apt server and now have a functional backup. I will end up closing this pr as it is not necessary.

**Comment by paulmenzel** [comment]
Nice, thank you for fixing the problem.

**Comment by taraschornyiplv** [comment]
@sonoble de we need this PR to be merged, or we can drop it?

**Pull request closed without merging**
