### PR TITLE
Remove kernels 5.4 and 5.8, move defaults for amd64 to 5.6.

### PR DESCRIPTION
**Pull request by sonoble**
Signed-off-by: Steve Noble <snoble@sonn.com>

### CODE REVIEW

**Review by willchao6790 — APPROVED** [review]
5.4->5.6, remove 5.4
5.8->5.10, remove 5.8
ok

**Review by taraschornyiplv — APPROVED** [review]

**Comment by chenglin-tsai** [comment]
To make the tx4810 ONLP working with kernel 5.10, it needs to update MFT PCI drivers, or the system boot up message will show the errors like below, which means the device node of "/dev/mst/mt52100_pciconf0" is failed to create.
```
ioctl (PCICONF_INIT): Inappropriate ioctl for device
ioctl (PCI_INIT): Inappropriate ioctl for device
cat: /dev/mst/mt52100_pci_cr0: No such file or directory
ioctl (PCICONF_INIT): Inappropriate ioctl for device
ioctl (PCI_INIT): Inappropriate ioctl for device
cat: /dev/mst/mt52100_pci_cr0: No such file or directory
ioctl (PCICONF_INIT): Inappropriate ioctl for device
ioctl (PCI_INIT): Inappropriate ioctl for device
cat: /dev/mst/mt52100_pci_cr0: No such file or directory
```

To fix this, we can update the MFT PCI drivers to latest version 4.16.3 from Mellanox official website:
https://www.mellanox.com/products/adapter-software/firmware-tools

And here is the final patch:
[0001-Update-MFT-PCI-drivers-to-latest-version-4.16.3-on-tx4810.txt](https://github.com/dentproject/dentOS/files/6240421/0001-Update-MFT-PCI-drivers-to-latest-version-4.16.3-on-tx4810.txt)

The test log shows tx4810 ONLP works fine using MFT PCI driver v4.16.3:
[dentOS_tx4810_test_onlp_with_mft_pci_driver_v4.16.3_20210401.log](https://github.com/dentproject/dentOS/files/6240460/dentOS_tx4810_test_onlp_with_mft_pci_driver_v4.16.3_20210401.log)

**Comment by sonoble** [comment]
> To make tx4810 ONLP working with kernel 5.10, it needs to update MFT PCI drivers, or the Linux boot up message will show the errors like below, which means the device node of "/dev/mst/mt52100_pciconf0" is failed to create.
> 
> ```
> ioctl (PCICONF_INIT): Inappropriate ioctl for device
> ioctl (PCI_INIT): Inappropriate ioctl for device
> cat: /dev/mst/mt52100_pci_cr0: No such file or directory
> ioctl (PCICONF_INIT): Inappropriate ioctl for device
> ioctl (PCI_INIT): Inappropriate ioctl for device
> cat: /dev/mst/mt52100_pci_cr0: No such file or directory
> ioctl (PCICONF_INIT): Inappropriate ioctl for device
> ioctl (PCI_INIT): Inappropriate ioctl for device
> cat: /dev/mst/mt52100_pci_cr0: No such file or directory
> ```
> 
> To fix this, we can update the MFT PCI drivers to latest version 4.16.3 from Mellanox official website:
> https://www.mellanox.com/products/adapter-software/firmware-tools
> 
> And here is the final patch (I will make another new PR if this patch won't be applied at this time):
> [0001-Update-MFT-PCI-drivers-to-latest-version-4.16.3-on-tx4810.txt](https://github.com/dentproject/dentOS/files/6240421/0001-Update-MFT-PCI-drivers-to-latest-version-4.16.3-on-tx4810.txt)
> 
> The test log shows tx4810 ONLP works fine using MFT PCI driver v4.16.3:
> [dentOS_tx4810_test_onlp_with_mft_pci_driver_v4.16.3_20210401.log](https://github.com/dentproject/dentOS/files/6240460/dentOS_tx4810_test_onlp_with_mft_pci_driver_v4.16.3_20210401.log)

Hi Chenglin,
Can you provide a pull request for these changes?

**Comment by chenglin-tsai** [comment]
> Hi Chenglin,
> Can you provide a pull request for these changes?

Hi Steven,
No problem, I has crated a new PR for this changes (https://github.com/dentproject/dentOS/pull/63), you can check it and let me know if there is any problems. Thanks.

**Pull request merged**
