### PR TITLE
Fix the wrong rxlos register number of swp8 in tn4810m and tn4810m-dn dts

### PR DESCRIPTION
**Pull request by chenglin-tsai**
The rxlos register of swp8 in tn4810m dts should be 0x40, not 0x41, and this wrong register number will make swp8 always having link down status using ethtool. This problem is discovered with marvell 2.8.0 firmware version.
 
Test log (using marvell 2.8.0 firmware):
[dentOS_tn4810m_check_swp8_fiber_connection_and_all_other_ports_ok_01272020.log](https://github.com/dentproject/dentOS/files/5884214/dentOS_tn4810m_check_swp8_fiber_connection_and_all_other_ports_ok_01272020.log)

Signed-off-by: Chenglin Tsai <chenglin.tsai@deltaww.com>

### CODE REVIEW

**Review by sonoble — DISMISSED** [review]

**Review by Mickey201 — APPROVED** [review]

**Comment by paulmenzel** [comment]
Looks good, three nits:

1.  Could you please add the merge/pull request description also as the commit message?
2.  There is a small typo: reigster → register
3.  In the signed-off-by line, could you please write your name as *Chenglin Tsai*?

**Comment by chenglin-tsai** [comment]
Hi @paulmenzel,

I has modified the descriptions as you requested, please let me know if I misunderstood your words. Thanks you.

**Comment by paulmenzel** [comment]
Yes, thank you. For item one, please do `git commit --amend -s`, and copy the description. After that, add the switch `-f` to your previous push command.

**Comment by chenglin-tsai** [comment]
> Yes, thank you. For item one, please do `git commit --amend -s`, and copy the description. After that, add the switch `-f` to your previous push command.

It works! I appreciate your detailed explanations for commands and has learned something form it. Many thanks.

**Review by sonoble — APPROVED** [review]

**Review by Mickey201 — APPROVED** [review]

**Pull request merged**
