### PR TITLE
Improve persistent workflow documentation

### PR DESCRIPTION
**Pull request by paulmenzel**

### CODE REVIEW

**Comment by taraschornyiplv** [comment]
recheck

**Comment by taraschornyiplv** [comment]
recheck

**Comment by taraschornyiplv** [comment]
recheck

**Comment by jwagantall** [comment]
recheck

**Comment by jwagantall** [comment]
recheck

**Comment by jwagantall** [comment]
Looks like the build should be working now..

**Review by taraschornyiplv — APPROVED** [review]

**Comment by taraschornyiplv** [comment]
recheck

**Comment by taraschornyiplv** [comment]
recheck

**Review by eladnachman — APPROVED** [review]

**Pull request merged**
