### PR TITLE
Modify DTS file for RX LOSS & SFP maximum power limit

### PR DESCRIPTION
**Pull request by richardlee66**
Correct Rx loss active low in DTS file and add the default value of SFP maximum power milliwatt to 2000

### CODE REVIEW

**Comment by sonoble** [comment]
Richard, can you please sign off on the code?

**Comment by richardlee66** [comment]
> Richard, can you please sign off on the code?

Hi Steve,
I did sign off the commits when I create pull request. I do not know why it does not pass the DCO.

**Comment by sonoble** [comment]
> > Richard, can you please sign off on the code?
> 
> Hi Steve,
> I did sign off the commits when I create pull request. I do not know why it does not pass the DCO.

Hi Richard it looks like the 2nd commit is not signed. 7c3..

**Comment by Mickey201** [comment]
Guys, it can't be committed yet as it missing additional changes in the CPLD platform driver.

**Comment by richardlee66** [comment]
missing commit sign off

**Pull request closed without merging**
