### PR TITLE
enable ipv6 filter tables

### LINKED ISSUE #72: Ip6tables kernel module missing
is this intentional?

### PR DESCRIPTION
**Pull request by aep**
fixes #72

### CODE REVIEW

**Comment by paulmenzel** [comment]
Thank you for your contribution.

1.  Should this also be enabled for x86?
2.  Could you please extend the commit message a little bit. For example, how much did the Linux kernel size increase, and on what device did you test this?

**Comment by aep** [comment]
it already is. hence this should be a nobrainer. looks more like a bugfix to me, since nobody is going to leave the ipv6 doors open in production

**Comment by paulmenzel** [comment]
Ah, thanks. Please amend the [commit message](https://chris.beams.io/posts/git-commit/) with that information.

**Comment by aep** [comment]
ok

**Review by taraschornyiplv — APPROVED** [review]

**Review by sonoble — APPROVED** [review]

**Comment by sonoble** [comment]
Merging is blocked due to the commit not being cryptographicly signed.

**Comment by aep** [comment]
@sonoble @taraschornyiplv

**Review by taraschornyiplv — APPROVED** [review]

**Comment by KanjiMonster** [comment]
Since we dropped support for kernel 5.10 with the move to Debian 10, can you please retarget for [kernel 5.15](https://github.com/dentproject/dentOS/blob/main/packages/base/any/kernels/5.15-lts/configs/arm64-all/arm64-all.config)?

**Comment by aep** [comment]
unfortunately after 2 years of having a one line change ignored, i don't think i want to do that, no

**Comment by KanjiMonster** [comment]
> unfortunately after 2 years of having a one line change ignored, i don't think i want to do that, no

Fair enough, can't blame you there

**Pull request closed without merging**
