### PR TITLE
[tn48m/tn48m-dn series] Upgrade Linux kernel to 5.15

### PR DESCRIPTION
**Pull request by CaryChen-Deltaww**
Upgrade tn48m/tn48m-dn series platform Linux kernel to 5.15

Additional pull request for related dts files also submitted to:
https://github.com/dentproject/linux/tree/dent-linux-5.15.y

Signed-off-by: cary.sc.chen <cary.sc.chen@deltaww.com>

### CODE REVIEW

**Comment by taraschornyiplv** [comment]
We need to merge https://github.com/dentproject/linux/pull/1 to fix an issue with failed Jenkins build

**Comment by taraschornyiplv** [comment]
also looks like commit is not signed

**Comment by snobleaws** [comment]
recheck

**Comment by CaryChen-Deltaww** [comment]
> also looks like commit is not signed

Updated commit with GPG signature

**Review by taraschornyiplv — APPROVED** [review]

**Review by sonoble — APPROVED** [review]

**Review by eladnachman — APPROVED** [review]

**Pull request merged**
