### PR TITLE
[as4564-26p] Add new platform

### PR DESCRIPTION
**Pull request by brandonchuang**
CPU: Marvel 88F7040
MAC: Marvell 98DX3500
PHY: Marvell 88E1780 x3 + 88E1512
DRAM: 8GB(CPU) / 4GB(MAC) DDR4 SDRAM
SSD: 32GB M.2 SATA SSD
AirFlow: Front To Back
Function port: 1 x USB port
               1 x RJ45 Mgmt port
               1 x RJ45 Console port
Ethernet Port: 24 x 1G
Uplink port: 2xSFP+

Signed-off-by: Brandon Chuang <brandon_chuang@edge-core.com>

### CODE REVIEW

**Review by taraschornyiplv — APPROVED** [review]

**Comment by Mickey201** [comment]
@brandonchuang, may you please update how this patch was verified?

**Comment by taraschornyiplv** [comment]
I've tried to install an image built from this pr and get this error 
```
ONIE:/ # onie-nos-install http://172.20.10.138/DENTOS-ac5x_ONL-OS9_2021-06-03.08
41-3ae13e8_ARM64_INSTALLED_INSTALLER 
discover: installer mode detected.
Stopping: discover... done.
Info: Attempting http://172.20.10.138/DENTOS-ac5x_ONL-OS9_2021-06-03.0841-3ae13e8_ARM64_INSTALLED_INSTALLER ...
Connecting to 172.20.10.138 (172.20.10.138:80)
installer            100% |*******************************|   403M  0:00:00 ETA
ONIE: Executing installer: http://172.20.10.138/DENTOS-ac5x_ONL-OS9_2021-06-03.0841-3ae13e8_ARM64_INSTALLED_INSTALLER
installer: computing checksum of original archive
installer: checksum is OK
installer: extracting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000078 seconds, 6.3MB/s
installer: copying file before resetting pad
installer: resetting pad
1+0 records in
1+0 records out
512 bytes (512B) copied, 0.000056 seconds, 8.7MB/s
installer: extracting shar into /tmp/sfx-hy0oBh
installer: invoking installer installer.sh
Found installer tmpfs on /tmp/sfx-hy0oBh (/tmp) using opts rw,noatime
Unpacking ONL installer files...
Extracting from /tmp/sfx-hy0oBh/onie-installer.zip: onl-loader-fit.itb ...
Archive:  /tmp/sfx-hy0oBh/onie-installer.zip
  inflating: onl-loader-fit.itb
Extracting initrd to /tmp/sfx-hy0oBh/initrd-JrmrCE
0+1 records in
0+1 records out
14555364 bytes (13.9MB) copied, 0.029727 seconds, 467.0MB/s
0+0 records in
0+0 records out
0 bytes (0B) copied, 0.000074 seconds, 0B/s
gzip: corrupted data
81434 blocks
Setting up /dev
Setting up /run
Setting up mounts
Launching ONL installer
Extracting from /tmp/sfx-hy0oBh/onie-installer.zip: preinstall.sh ...
Archive:  /tmp/sfx-hy0oBh/onie-installer.zip
  inflating: preinstall.sh
Invoking pre-install actions
Hello from preinstall
Chroot is /tmp/sfx-hy0oBh/initrd-JrmrCE
getting installer configuration
+ blkid
found ONIE MTD device /dev/mtd2
parsing FIT image in /dev/mtdblock2
default profile is accton_as4564_26p
retrieving ramdisk initramfs
reading initrd at [6b7d7c:97971c]
+ cat > /tmp/sfx-hy0oBh/initrd-282P5u.img
extracting initrd /tmp/sfx-hy0oBh/initrd-282P5u.img
+ /bin/mkdir /tmp/sfx-hy0oBh/chroot-LfkkX_.d
+ xz -dc /tmp/sfx-hy0oBh/initrd-282P5u.img | cpio -imd
18617 blocks
preparing chroot in /tmp/sfx-hy0oBh/chroot-LfkkX_.d
+ mount -v -t proc proc /tmp/sfx-hy0oBh/chroot-LfkkX_.d/proc
+ mount -v -t sysfs sysfs /tmp/sfx-hy0oBh/chroot-LfkkX_.d/sys
+ modprobe -v efivarfs
+ mount -v -t devtmpfs devtmpfs /tmp/sfx-hy0oBh/chroot-LfkkX_.d/dev
+ mount -v -t devpts devpts /tmp/sfx-hy0oBh/chroot-LfkkX_.d/dev/pts
extracting initrd /tmp/sfx-hy0oBh/initrd-282P5u.img
+ /bin/mkdir /tmp/sfx-hy0oBh/chroot-r9rQId.d
+ xz -dc /tmp/sfx-hy0oBh/initrd-282P5u.img | cpio -imd
18617 blocks
preparing chroot in /tmp/sfx-hy0oBh/chroot-r9rQId.d
+ mount -v -t proc proc /tmp/sfx-hy0oBh/chroot-r9rQId.d/proc
+ mount -v -t sysfs sysfs /tmp/sfx-hy0oBh/chroot-r9rQId.d/sys
+ modprobe -v efivarfs
+ mount -v -t devtmpfs devtmpfs /tmp/sfx-hy0oBh/chroot-r9rQId.d/dev
+ mount -v -t devpts devpts /tmp/sfx-hy0oBh/chroot-r9rQId.d/dev/pts
+ chroot /tmp/sfx-hy0oBh/chroot-r9rQId.d /bin/sh -c IFS=;onie-sysinfo -h
un-mounting mounts points in chroot /tmp/sfx-hy0oBh/chroot-r9rQId.d
+ umount -v /tmp/sfx-hy0oBh/chroot-r9rQId.d/sys
+ umount -v /tmp/sfx-hy0oBh/chroot-r9rQId.d/proc
+ umount -v /tmp/sfx-hy0oBh/chroot-r9rQId.d/dev/pts
+ umount -v /tmp/sfx-hy0oBh/chroot-r9rQId.d/dev
cleaning up chroot in /tmp/sfx-hy0oBh/chroot-r9rQId.d
+ /bin/rm -fr /tmp/sfx-hy0oBh/chroot-r9rQId.d
+ /bin/rm /tmp/sfx-hy0oBh/initrd-282P5u.img
un-mounting mounts points in chroot /tmp/sfx-hy0oBh/chroot-LfkkX_.d
+ umount -v /tmp/sfx-hy0oBh/chroot-LfkkX_.d/sys
+ umount -v /tmp/sfx-hy0oBh/chroot-LfkkX_.d/proc
+ umount -v /tmp/sfx-hy0oBh/chroot-LfkkX_.d/dev/pts
+ umount -v /tmp/sfx-hy0oBh/chroot-LfkkX_.d/dev
cleaning up chroot in /tmp/sfx-hy0oBh/chroot-LfkkX_.d
+ /bin/rm -fr /tmp/sfx-hy0oBh/chroot-LfkkX_.d
ONL Installer DENT OS DENTOS-ac5x, 2021-06-03.08:41-3ae13e8
ONL installer running chrooted.
Detected platform arm64-accton-as4564-26p-r0
trying a U-Boot based installer
using proxy GRUB
+ /usr/sbin/fw_setenv --help
installer failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/onl/install/App.py", line 212, in runLocalOrChroot
    code = self.installer.run()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1327, in run
    return self.installUboot()
  File "/usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py", line 1212, in installUboot
    st = os.stat(self.device)
OSError: [Errno 2] No such file or directory: '/dev/sda'
re-attaching to tty
entering Python debugger (installer_debug=1)
> /usr/lib/python2.7/dist-packages/onl/install/BaseInstall.py(1212)installUboot()
-> st = os.stat(self.device)
(Pdb) c
Install failed.
```

**Review by taraschornyiplv — CHANGES_REQUESTED** [review]
install of image failed

**Comment by sonoble** [comment]
> install of image failed

Did you run this on a 4564 or did you change the platform id on a different machine?

**Comment by taraschornyiplv** [comment]
yes I've tried on 4564

**Comment by brandonchuang** [comment]
> @brandonchuang, may you please update how this patch was verified?

Here is the output of onlpdump:
root@localhost:~# onlpdump
   System Information: = {
       MAC: 00:00:00:00:00:00
       Diag Version: 00.0a.00.02
   }
   thermal @ 1 = {
       Description: Thermal 1 - U12_CPU_MAC (0x48)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 30000
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 2 = {
       Description: Thermal 2 - U1_AIR_OUTLET (0x49)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 27500
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 3 = {
       Description: Thermal 3 - U88_AIR_INLET (0x4B)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 25500
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 4 = {
       Description: Thermal 4 - U29_PSU (0x4C)
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 27500
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   psu @ 1 = {
       Description: PSU-1
       Model:  NULL
       SN:     NULL
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000000
       Vin:    0
       Vout:   0
       Iin:    0
       Iout:   0
       Pin:    0
       Pout:   0
   }

SFPs:
  Presence Bitmap: None
  RX_LOS Bitmap: None

Port 25: Missing.
Port 26: Missing.

Additional information:
root@localhost:~# uname -r
5.10.4
root@localhost:~# cat /etc/onl/platform
arm64-accton-as4564-26p-r0

root@localhost:~# [  294.949197] sfp sfp-25: module DELTA            LCP-1250B4QDRT   rev 000
[  294.949197]  sn 0000070904100001 dc 07030200

root@localhost:~# [  298.496188] sfp sfp-25: module removed

**Comment by brandonchuang** [comment]
> yes I've tried on 4564

I can install successfully with my commit, the steps are as follows:
git clone https://github.com/dentproject/dentOS.git
dentOS/
git remote add upstream https://github.com/brandonchuang/dentOS.git
git fetch upstream
git cherry-pick 3ae13e87a9f912ce429df607582326e925f3b4fd

And the NOS can be installed:
ONIE: NOS install successful: tftp://192.168.1.99/DENTOS-main_ONL-OS9_2021-06-04.0225-c8572bb_ARM64_INSTALLED_INSTALLER

Can you execute the onie_uninstall command in uboot then install again?
#run onie_uninstall

**Comment by taraschornyiplv** [comment]
I've tried with onie_unistall and it did not help.
it looks like onie installer can not find a disk to install an image 
```
OSError: [Errno 2] No such file or directory: '/dev/sda'
re-attaching to tty
entering Python debugger (installer_debug=1)
```

**Comment by brandonchuang** [comment]
> I've tried with onie_unistall and it did not help.
> it looks like onie installer can not find a disk to install an image
> 
> ```
> OSError: [Errno 2] No such file or directory: '/dev/sda'
> re-attaching to tty
> entering Python debugger (installer_debug=1)
> ```

Does it happen on all units you have?
Can you try on another device?

**Comment by taraschornyiplv** [comment]
> Does it happen on all units you have?
> Can you try on another device?

yes, it happens on all units

**Review by taraschornyiplv — APPROVED** [review]

**Comment by richardlee66** [comment]
> > Does it happen on all units you [have?](url)
> > Can you try on another device?
> 
> yes, it happens on all units



1. can you open the housing to see if the SSD in put in the location as the attachment ?
or you can attach the photo as me to show ?
2021-06-04_SSD location

2. can you show the output  of the command "ONIE:/ # cat /etc/machine.conf"?

**Comment by taraschornyiplv** [comment]
SSD was in diferent slot. changing slot resolved the issue 

```
ONIE:/ # cat /etc/machine.conf 
onie_version=2020.02.00.12
onie_vendor_id=259
onie_build_machine=accton_as4564_26p
onie_machine_rev=0
onie_arch=arm64
onie_build_platform=arm64-accton_as4564_26p-r0
onie_config_version=1
onie_build_date="2021-04-29T17:04+08:00"
onie_partition_type=gpt
onie_kernel_version=4.14.76
onie_firmware=
onie_switch_asic=mvl
onie_skip_ethmgmt_macs=yes
onie_machine=accton_as4564_26p
onie_platform=arm64-accton_as4564_26p-r0

```

**Review by sonoble — APPROVED** [review]
Was able to run on a RNS in our lab : 

root@localhost:~# onlpdump -s
 System Information:
   Product Name: AS4564-26P-O-AC-F

**Comment by brandonchuang** [comment]
@sonoble 
I need to add the auto fan controller (thermal policy) into this platform.
Should I add another commit into this PR, or you can merge it first then I will be able to send a new PR for it?

Thanks.

**Comment by sonoble** [comment]
Merged send a new pr.

**Comment by brandonchuang** [comment]
Thank you so much!

**Pull request merged**
